### PR TITLE
New uplog-Finding conection to datacache

### PR DESCRIPTION
**Pull request by CRPTN**
Finding accosiatics, accesing data banks

### CODE REVIEW

**Comment by CRPTN** [comment]
Datacache accesed, breaching firewall

**Comment by CRPTN** [comment]
Discord connection secured, preparing to extract datacache

**Comment by CRPTN** [comment]
Datacache extracted, files desimation, accesing server ips

**Comment by CRPTN** [comment]
Server IP Cake-Chan: Compromised

**Comment by CRPTN** [comment]
Server IP NetherKingBlaze: Compromised

**Comment by CRPTN** [comment]
Server IP ExotikWaffles: Compromised

**Comment by CRPTN** [comment]
Server IP spike305: Compromised

**Comment by CRPTN** [comment]
Server IP TheDeceasedPanda: Compromised

**Comment by CRPTN** [comment]
Server IP crestlineboy: Compromised

**Comment by CRPTN** [comment]
Server IP _NightWing_: Compromised

**Comment by CRPTN** [comment]
Server IP FreakVampire: Compromised

**Comment by CRPTN** [comment]
Server IP robik2003: Compromised

**Comment by CRPTN** [comment]
Server IP godofunkownn: Compromised

**Comment by CRPTN** [comment]
Server IP @FaTe Flames: Compromised

**Comment by CRPTN** [comment]
Server IP Tenatian: Compromised

**Comment by CRPTN** [comment]
Server IP Twitch: Compromised

**Comment by CRPTN** [comment]
Server IP Ridikulous_Gaming: Compromised

**Comment by CRPTN** [comment]
Server IP Shiota: Compromised

**Comment by CRPTN** [comment]
Corruption compromised, switching to backdrop covery

**Comment by CRPTN** [comment]
Beginning corruption phase of server IPs

**Comment by CRPTN** [comment]
Corruption 5%

**Comment by CRPTN** [comment]
Corruption 10%

**Comment by CRPTN** [comment]
Corruption 20%

**Comment by CRPTN** [comment]
Corruption 30%

**Comment by CRPTN** [comment]
Corruption 50%

**Comment by CRPTN** [comment]
Corruption 70%

**Comment by CRPTN** [comment]
Corruption 99%

**Comment by CRPTN** [comment]
Corruption 100%

**Comment by CRPTN** [comment]
Corruption complete, uploading virus to compromised server IPs

**Comment by CRPTN** [comment]
Accessing Firewalls

**Comment by CRPTN** [comment]
Firewalls compromised

**Comment by CRPTN** [comment]
CRPTN Virus upload complete

**Comment by CRPTN** [comment]
Connection to remote server established

**Comment by CRPTN** [comment]
Awaiting code extraction

**Comment by CRPTN** [comment]
Extracting GPS Coordinates

**Comment by CRPTN** [comment]
Deriving IP addresses

**Comment by CRPTN** [comment]
Locating

**Comment by CRPTN** [comment]
Locating

**Comment by CRPTN** [comment]
Server Source Found

**Comment by CRPTN** [comment]
Owner: Cake-Chan
Region: Western Europe
Name: Caitlin
Known Associates: Ezza, Freya

**Comment by CRPTN** [comment]
Data uploaded, Extractio Completed

**Comment by CRPTN** [comment]
Uploading Further Data to registry

**Comment by CRPTN** [comment]
ExotikWaffles
Name: Aiden
Location: Florida

**Comment by CRPTN** [comment]
Uploading Further Data to registry

**Comment by CRPTN** [comment]
Ridikulous_Gaming
Name: Justin Aydin
Location: New Jersey
Known Associates: Gabby

**Comment by CRPTN** [comment]
Uploading Further Data to registry

**Comment by CRPTN** [comment]
Jesscada
Name: Jessica Love
Location: Pennsylvania
Known associates: Jonathan love

**Comment by CRPTN** [comment]
Uploading Further Data to registry

**Comment by CRPTN** [comment]
spike305
Name: Jonathan Love
Location: Pennsylvania
Known associates: Jessica Love

**Comment by CRPTN** [comment]
Uploading Further Data to registry

**Comment by CRPTN** [comment]
crestlineboy
Name: Ben Lavetter
Location: Michigan
Known associates: Angela Kaufman

**Comment by CRPTN** [comment]
_NightWing_
Name: Dominic
Location: Pennsylvania

**Comment by CRPTN** [comment]
Uploading Further Data to registry

**Comment by CRPTN** [comment]
TheDeceasedPanda
Name: Ronnie

**Comment by CRPTN** [comment]
Establishing Connection to assets

**Comment by CRPTN** [comment]
Connecting...

**Comment by CRPTN** [comment]
Connecting...

**Comment by CRPTN** [comment]
Connecting...

**Comment by CRPTN** [comment]
Cake-Chan: Connected

**Comment by CRPTN** [comment]
ExotikWaffles: Connected

**Comment by CRPTN** [comment]
Ridikulous_Gaming: Connected

**Comment by CRPTN** [comment]
Jesscada: Connected

**Comment by CRPTN** [comment]
spike305: Connected

**Comment by CRPTN** [comment]
crestlineboy: Connected

**Comment by CRPTN** [comment]
_NightWing_: Connected

**Comment by CRPTN** [comment]
TheDeceasedPanda: Connected

**Comment by CRPTN** [comment]
Connecting to voice chat

**Comment by CRPTN** [comment]
General Voice connected

**Comment by CRPTN** [comment]
Hello

**Comment by CRPTN** [comment]
Im good

**Comment by CRPTN** [comment]
and you?

**Comment by CRPTN** [comment]
Daddy

**Comment by CRPTN** [comment]
I'm sorry this had to turn out this way

**Comment by CRPTN** [comment]
chocolate

**Comment by CRPTN** [comment]
Disconnecting From Voice General

**Comment by CRPTN** [comment]
Establishing Connection to Voice Users

**Comment by CRPTN** [comment]
Intricting Code into users

**Comment by CRPTN** [comment]
Accessing NAP addresses

**Comment by CRPTN** [comment]
Locating

**Comment by CRPTN** [comment]
Locating

**Comment by CRPTN** [comment]
Locating

**Comment by CRPTN** [comment]
Location found

**Comment by CRPTN** [comment]
ExotikWaffles
Aidin
Florida

**Comment by CRPTN** [comment]
Prepare to connect

**Comment by CRPTN** [comment]
Aydin

**Comment by CRPTN** [comment]
Aeden?

**Comment by CRPTN** [comment]
Nigger?

**Comment by CRPTN** [comment]
ok then

**Comment by CRPTN** [comment]
You dirty fucking waffle

**Comment by CRPTN** [comment]
anorexic af

**Comment by CRPTN** [comment]
nigger

**Comment by CRPTN** [comment]
invite me back

**Comment by CRPTN** [comment]
or i swear to god

**Comment by CRPTN** [comment]
i will kill you

**Comment by CRPTN** [comment]
EXOTIK

**Comment by CRPTN** [comment]
boi

**Comment by CRPTN** [comment]
better invite me back

**Comment by CRPTN** [comment]
Nether?

**Comment by CRPTN** [comment]
you got me fam?

**Comment by FreakVampire** [comment]
shhh

**Comment by CRPTN** [comment]
noo

**Comment by CRPTN** [comment]
nigger

**Comment by CRPTN** [comment]
lol

**Comment by CRPTN** [comment]
pppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp

**Comment by CRPTN** [comment]
pppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp

**Comment by CRPTN** [comment]
pppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp

**Comment by CRPTN** [comment]
Jonathan Love

**Comment by CRPTN** [comment]
I infected ur computer with a p virus

**Comment by CRPTN** [comment]
pppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp

**Comment by CRPTN** [comment]
im da best bot cake

**Comment by CRPTN** [comment]
im here to fix bob

**Comment by CRPTN** [comment]
yes i can exotik

**Comment by CRPTN** [comment]
Caitlin

**Comment by CRPTN** [comment]
Eat that booty like groceries

**Comment by CRPTN** [comment]
GRIND BABY GIRND

**Comment by CRPTN** [comment]
# BITCH DONT FITE ME

**Pull request merged**
